### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by dfloo** [dfloo/501px#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by jenvomo** [comment]
- [x] Fix error border to match 500px login errors (border, background color, text content)
- [x] Add 'Discover' 'About' 'Studio' as fake links for now (will make them real when you make each new component)
- [x] Update color/style of signup button to match the login page (green button) I know we talked about the main navbar but the green is a small update to make it match 500px exactly.

**Comment by jenvomo** [comment]
Error styling is looking great! 
- [x] Update error message for login page to match 500px "The email or username you entered is incorrect."
- [x] Nav bar is a bit too thick / tall
- [x] Text for "Signup" and "Login" buttons in the top right are too small
- [x] Font weight for form title and buttons is too thick

**Comment by jenvomo** [comment]
- [x] Align 'Discover' 'About' 'Studio' in the center of the navbar
